# Generated by Django 5.1 on 2024-08-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_estudante_cpf_alter_estudante_num_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='num_celular',
            field=models.IntegerField(max_length=14, unique=True),
        ),
    ]
