# Generated by Django 5.1 on 2024-08-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], default='M', max_length=1),
        ),
    ]
