# Generated by Django 5.1 on 2024-09-18 19:09

import localflavor.br.models
import localflavor.br.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_alter_cursos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True, validators=[localflavor.br.validators.BRCPFValidator]),
        ),
    ]
