# Generated by Django 5.1 on 2024-09-18 21:38

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_alter_estudante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
    ]
